FROM node:16.13.0 as react-prod
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
ENV REACT_APP_NAME=sabrina
RUN npm run build

FROM nginx
COPY --from=react-prod /app/build /usr/share/nginx/html